<a href="https://colab.research.google.com/github/AndreaCastiella/Tensorflow2.0-Course-freeCodeCamp/blob/main/Moule2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 2.0 Complete Course freeCodeCamp

Module 1 was just an introduction.


# Importing Tensorflow in Google Colab

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Creating Tensors

In [4]:
string =tf.Variable('This is a string', tf.string)
number = tf.Variable(128, tf.int16)
floating = tf.Variable(2.123, tf.float32)

## Rank/Degree Tensors

In [2]:
rank1_tensor = tf.Variable(['Test', 'Ok'], tf.string)
rank2_tensor = tf.Variable([['Test', 'Ok'], ['Test2', 'Nok']], tf.string)

###### To determine the rank of a tensor we can call the following method

In [5]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## Shape of Tensors


In [6]:
rank2_tensor.shape

TensorShape([2, 2])

## Changing Shape

In [11]:
tensor1 = tf.ones([1,2,3])
print(tensor1)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the diemnsion in that place.
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
